platform :ios, '9.0'
use_frameworks!

target 'HCVimeoVideoExtractor_Example' do
  pod 'HCVimeoVideoExtractor', :path => '../'

  target 'HCVimeoVideoExtractor_Tests' do
    inherit! :search_paths

    
  end
end
